servicecatalog/oscm-interfaces

- oscm-extsvc-internal/src/main/java/org/oscm/internal/types/enumtypes/AuthenticationMode.java
This belongs to https://github.com/servicecatalog/oscm/pull/390.
After this PR is merged in sso branch the OSCM sso branch will be updated to fetch the interfaces from there.
> Remove SAML auth mode.

- oscm-extsvc-internal/src/main/java/org/oscm/internal/vo/VOOrganization.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/26)
> Add oidc group id.

- oscm-extsvc-internal/pom.xml
- pom.xml
Fixes #28 on javadoc generation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/29)
> javadoc build fix

- pom.xml
- fixed maven javadoc plugin configuration
**OSCM Build References:**
N/A
Closes #33 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/34)
> Fixed maven javadoc plugin configuartion

- oscm-extsvc-internal/src/main/java/org/oscm/internal/intf/IdentityService.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/35)
> remove token

- oscm-app-extsvc/src/main/java/org/oscm/app/v2_0/BSSWebServiceFactory.java
- oscm-app-extsvc/src/main/java/org/oscm/app/v2_0/intf/APPlatformService.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/37)
> Changes for WS client

- oscm-extsvc-internal/src/main/java/org/oscm/internal/types/exception/RegistrationException.java
- oscm-extsvc/src/main/java/org/oscm/types/exceptions/RegistrationException.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/39)
> add new reason

- oscm-extsvc-internal/src/main/java/org/oscm/internal/intf/IdentityService.java
* IdentityService remote interface enhanced for accessing OIDC user synchronization  
* Polished up added javadocs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/40)
> Added interface to synchronize users with OIDC provider

- oscm-app-extsvc/src/main/resources/org/oscm/app/v2_0/i18n/messages_de.properties
- oscm-app-extsvc/src/main/resources/org/oscm/app/v2_0/i18n/messages_en.properties
- oscm-app-extsvc/src/main/resources/org/oscm/app/v2_0/i18n/messages_ja.properties
* Just version names to 18.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/41)
> [SSO] Updated version names

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/task.md
- .github/pull_request_template.md
This issue is a part of https://github.com/servicecatalog/oscm/issues/501
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/43)
> Added issue and pr templates

- oscm-extsvc-internal/src/main/java/org/oscm/internal/intf/OperatorService.java
- A query interface for the new organization chooser.
**OSCM Build References:**
No functional impact.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/46)
> New method getOrganizationIdentifiers.

- oscm-extsvc-internal/src/main/java/org/oscm/internal/intf/BrandService.java
- add interfaces for mobile stage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/48)
> add interface methods for mobile stage

- oscm-extsvc-internal/src/main/java/org/oscm/internal/intf/BrandService.java
- add new method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/49)
> Add new method

- oscm-app-extsvc/src/main/resources/org/oscm/app/v2_0/i18n/messages_de.properties
- oscm-app-extsvc/src/main/resources/org/oscm/app/v2_0/i18n/messages_en.properties
- oscm-app-extsvc/src/main/resources/org/oscm/app/v2_0/i18n/messages_ja.properties
- New version numbers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/51)
> New version numbers

- oscm-extsvc-internal/src/main/java/org/oscm/internal/types/enumtypes/ConfigurationKey.java
- Add new config setting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/52)
> Add new config setting

- oscm-app-extsvc/src/main/java/org/oscm/app/v2_0/intf/APPlatformService.java
- New platform service interface to obtained filtered instance list.
> List instances with filter.

- oscm-app-extsvc/src/main/java/org/oscm/app/v2_0/intf/APPlatformService.java
- New APPlatformService method for listing instances of organization
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/55)
> List instances of organization

- oscm-app-extsvc/src/main/resources/org/oscm/app/v2_0/i18n/messages_de.properties
- oscm-app-extsvc/src/main/resources/org/oscm/app/v2_0/i18n/messages_en.properties
- oscm-app-extsvc/src/main/resources/org/oscm/app/v2_0/i18n/messages_ja.properties
- Updated version labels for UI about dialogs
**OSCM Build References:**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/58)
> New OSCM version

- README.md
- Adapt build badge in readme after migrating to travis-ci.com
**OSCM Build References:**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/59)
> Adapt travis-ci badge

- .github/workflows/maven.yml
- README.md
Added maven CI build workflow
- Added maven build workflow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-interfaces/60)
> Added maven build workflow
